SELECT COUNT(*) FROM Data WHERE ID > 81 AND ID < 84;
SELECT COUNT(*) FROM Data WHERE ID > 32 AND ID < 46;
SELECT COUNT(*) FROM Data WHERE ID > 53 AND ID < 57;
SELECT COUNT(*) FROM Data WHERE ID > 9 AND ID < 16;
SELECT COUNT(*) FROM Data WHERE ID > 36 AND ID < 44;
SELECT COUNT(*) FROM Data WHERE ID > 60 AND ID < 66;
SELECT COUNT(*) FROM Data WHERE ID > 10 AND ID < 24;
SELECT COUNT(*) FROM Data WHERE ID > 2 AND ID < 7;
SELECT COUNT(*) FROM Data WHERE ID > 8 AND ID < 11;
SELECT COUNT(*) FROM Data WHERE ID > 64 AND ID < 66;

