SELECT COUNT(*) FROM Data WHERE C < 68 AND A > 50;
SELECT COUNT(*) FROM Data WHERE A > 76 AND B < 38;
SELECT COUNT(*) FROM Data WHERE B < 40 AND C > 90;
SELECT COUNT(*) FROM Data WHERE B > 38 AND C < 11;
SELECT COUNT(*) FROM Data WHERE C < 44 AND B > 57;
SELECT COUNT(*) FROM Data WHERE B > 75 AND A < 93;
SELECT COUNT(*) FROM Data WHERE B > 7 AND C < 4;
SELECT COUNT(*) FROM Data WHERE A > 81 AND B < 12;
SELECT COUNT(*) FROM Data WHERE C < 19 AND B < 39;
SELECT COUNT(*) FROM Data WHERE B < 24 AND A < 40;

